### PR TITLE
fix(cli): prevent multiple commands produce when static product depends on same-named xcframework

### LINKED ISSUE #9744: `Multiple commands produce` with an external static product and its transitive binary
### What happened?

When adding an external dependency which has a static product depending on a xcframework with the same name, the build fails with "multiple commands produce" error.
A `.framework` and an `.xcframework` with the same name are linked to the target:
Image

[tuistexample1.zip](https://github.com/user-attachments/files/25795446/tuistexample1.zip)

### How do we reproduce it?

1. Use the attached sample project
2. `tuist install`
3. `tuist generate --cache profile none`

### Error log

```sh

Showing All Issues

Prepare build
error: Multiple commands produce '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/YandexPaySDK'
    note: Command: ProcessXCFramework /Users/eminiakhmetov/tuistexample1/tuistexample1/Tuist/.build/checkouts/yandex-pay-ios/YandexPaySDK/Frameworks/Static/YandexPaySDK.xcframework /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework ios simulator
    note: Target 'YandexPaySDK_Facade' (project 'YandexPaySDK'): Libtool /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/YandexPaySDK normal
error: Multiple commands produce '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework'
    note: Command: ProcessXCFramework /Users/eminiakhmetov/tuistexample1/tuistexample1/Tuist/.build/checkouts/yandex-pay-ios/YandexPaySDK/Frameworks/Static/YandexPaySDK.xcframework /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework ios simulator
    note: Target 'YandexPaySDK_Facade' (project 'YandexPaySDK') has create directory command with output '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework'


Multiple commands produce '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/YandexPaySDK'

Multiple commands produce '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework'


Build target YandexPaySDK_Facade of project YandexPaySDK with configuration Debug
warning: duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/_CodeSignature' on task: CodeSign /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework (in target 'YandexPaySDK_Facade' from project 'YandexPaySDK')
warning: duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework' on task: MkDir /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework (in target 'YandexPaySDK_Facade' from project 'YandexPaySDK')
warning: duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Headers' on task: MkDir /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Headers (in target 'YandexPaySDK_Facade' from project 'YandexPaySDK')
warning: duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Info.plist' on task: ProcessInfoPlistFile /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Info.plist /Users/eminiakhmetov/tuistexample1/tuistexample1/Tuist/.build/tuist-derived/YandexPaySDK_Facade/InfoPlists/YandexPaySDK_Facade-Info.plist (in target 'YandexPaySDK_Facade' from project 'YandexPaySDK')
warning: duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Modules/YandexPaySDK.swiftmodule/arm64-apple-ios-simulator.abi.json' on task: Copy /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Modules/YandexPaySDK.swiftmodule/arm64-apple-ios-simulator.abi.json /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Intermediates.noindex/YandexPaySDK.build/Debug-iphonesimulator/YandexPaySDK_Facade.build/Objects-normal/arm64/YandexPaySDK.abi.json (in target 'YandexPaySDK_Facade' from project 'YandexPaySDK')
warning: duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Modules/YandexPaySDK.swiftmodule/arm64-apple-ios-simulator.swiftdoc' on task: Copy /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Modules/YandexPaySDK.swiftmodule/arm64-apple-ios-simulator.swiftdoc /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Intermediates.noindex/YandexPaySDK.build/Debug-iphonesimulator/YandexPaySDK_Facade.build/Objects-normal/arm64/YandexPaySDK.swiftdoc (in target 'YandexPaySDK_Facade' from project 'YandexPaySDK')
warning: duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Modules/module.modulemap' on task: Copy /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Modules/module.modulemap /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Intermediates.noindex/YandexPaySDK.build/Debug-iphonesimulator/YandexPaySDK_Facade.build/module.modulemap (in target 'YandexPaySDK_Facade' from project 'YandexPaySDK')
warning: duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/YandexPaySDK' on task: Libtool /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/YandexPaySDK normal (in target 'YandexPaySDK_Facade' from project 'YandexPaySDK')
warning: duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Headers/YandexPaySDK-Swift.h' on task: SwiftMergeGeneratedHeaders /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Headers/YandexPaySDK-Swift.h /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Intermediates.noindex/YandexPaySDK.build/Debug-iphonesimulator/YandexPaySDK_Facade.build/Objects-normal/arm64/YandexPaySDK-Swift.h (in target 'YandexPaySDK_Facade' from project 'YandexPaySDK')


duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/_CodeSignature' on task: CodeSign /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework

duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework' on task: MkDir /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework

duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Headers' on task: MkDir /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Headers

duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Info.plist' on task: ProcessInfoPlistFile /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Info.plist /Users/eminiakhmetov/tuistexample1/tuistexample1/Tuist/.build/tuist-derived/YandexPaySDK_Facade/InfoPlists/YandexPaySDK_Facade-Info.plist

duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Modules/YandexPaySDK.swiftmodule/arm64-apple-ios-simulator.abi.json' on task: Copy /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Modules/YandexPaySDK.swiftmodule/arm64-apple-ios-simulator.abi.json /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Intermediates.noindex/YandexPaySDK.build/Debug-iphonesimulator/YandexPaySDK_Facade.build/Objects-normal/arm64/YandexPaySDK.abi.json

duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Modules/YandexPaySDK.swiftmodule/arm64-apple-ios-simulator.swiftdoc' on task: Copy /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Modules/YandexPaySDK.swiftmodule/arm64-apple-ios-simulator.swiftdoc /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Intermediates.noindex/YandexPaySDK.build/Debug-iphonesimulator/YandexPaySDK_Facade.build/Objects-normal/arm64/YandexPaySDK.swiftdoc

duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Modules/module.modulemap' on task: Copy /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Modules/module.modulemap /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Intermediates.noindex/YandexPaySDK.build/Debug-iphonesimulator/YandexPaySDK_Facade.build/module.modulemap

duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/YandexPaySDK' on task: Libtool /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/YandexPaySDK normal

duplicate output file '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Headers/YandexPaySDK-Swift.h' on task: SwiftMergeGeneratedHeaders /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Products/Debug-iphonesimulator/YandexPaySDK.framework/Headers/YandexPaySDK-Swift.h /Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample1-hiqxsstxxdfzgdckyquyewjdmjdn/Build/Intermediates.noindex/YandexPaySDK.build/Debug-iphonesimulator/YandexPaySDK_Facade.build/Objects-normal/arm64/YandexPaySDK-Swift.h

Build failed    06.03.2026, 16:04    1.1 seconds
```

### macOS version

26.3.1

### Tuist version

4.155.1

### Xcode version

26.2

### PR DESCRIPTION
**Pull request by pepicrft**
## Summary

When an external SPM package has a static product whose facade target depends on a binary target pointing to an xcframework with the same basename as the product, Xcode fails with "Multiple commands produce" because both the facade target and the xcframework produce output at the same path.

The `effectiveModuleName` function already handles the case where a dependency target's name directly matches the product name, but it missed the case where a binary target has a different name (e.g. `MySDK_Static`) while its xcframework path basename matches the product (e.g. `MySDK.xcframework` for product `MySDK`). This extends the BFS to also check binary target xcframework basenames when detecting naming conflicts.

## Test plan

- [x] Added test for the xcframework basename matching scenario
- [x] All existing `effectiveModuleName`-related tests pass

Closes #9744

### CODE REVIEW

File: cli/Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift [hunk 1]
```diff
@@ -408,7 +408,13 @@ public struct PackageInfoMapper: PackageInfoMapping {
                     return targetName
                 }
 
-                if targetsByName[dependencyName] != nil {
+                if let depTarget = targetsByName[dependencyName] {
+                    if depTarget.type == .binary,
+                       let depPath = depTarget.path,
+                       URL(fileURLWithPath: depPath).deletingPathExtension().lastPathComponent == singleProduct.name
```
Comment (fortmarek) [inline cli/Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift]: can't we use `AbsolutePath` for this over `URL`?

Comment (pepicrft) [reply cli/Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift]: Yes!
