### PR TITLE
Fix caching regression with Firebase

### LINKED ISSUE #5622: `tuist cache warm` fails when `Dependencies.swift` includes `Firebase` and specifies `macOS` as a supported platform
### What happened?

With Tuist 3.34.0 and Multiplatform support, including Firebase and using `macOS` causes `tuist cache warm` to fail. 

### How do we reproduce it?

1) Add the firebase package to via `Dependencies.swift` or `Package.swift`: https://github.com/firebase/firebase-ios-sdk.git
2) In `Dependencies.swift` add `.macOS` as a supported SPM platform.
3) run `tuist cache warm`

### Error log

```
he following build commands failed:
	CompileC /Users/msimons/Library/Developer/Xcode/DerivedData/Etsy-eulgklrmofhyjifbppyyzuklloei/Build/Intermediates.noindex/Firebase.build/Debug/FirebasePerformance.build/Objects-normal/arm64/FPRTraceBackgroundActivityTracker.o /Users/msimons/development/EtsyApp/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/firebase-ios-sdk/FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FirebasePerformance' from project 'Firebase')
(1 failure)
The 'xcodebuild' command exited with error code 65 and message:
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006001-001831C40C04801E }
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006001-001831C40C04801E }
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/msimons/Library/Developer/Xcode/DerivedData/Etsy-eulgklrmofhyjifbppyyzuklloei/Build/Intermediates.noindex/Firebase.build/Debug/FirebasePerformance.build/Objects-normal/arm64/FPRTraceBackgroundActivityTracker.o /Users/msimons/development/EtsyApp/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/firebase-ios-sdk/FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FirebasePerformance' from project 'Firebase')
(1 failure)

```

### macOS version

14.1

### Tuist version

3.34.0

### Xcode version

15.0

### PR DESCRIPTION
**Pull request by waltflanagan**
Resolves #5622

### Short description 📝

1) Strip unsupported platforms from known firebase targets that need them removed.  These are defined in the Firebase `Package.swift` file as well as here: https://github.com/firebase/firebase-ios-sdk/tree/master/SwiftPM-PlatformExclude

2) Fix an issue where we did not add conditions to the dependencies for a given target. this meant dependent targets would attempt to be build when building another platform they may not be compatible with.

### How to test the changes locally 🧐

Run `cache warm` against `fixtures/multiplatform_app_with_sdk`

### Contributor checklist ✅

- [x] The code has been linted using run `make workspace/lint-fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

File: Sources/TuistCore/GraphTraverser/GraphTraversing.swift [hunk 1]
```diff
@@ -86,6 +86,8 @@ public protocol GraphTraversing {
     ///   - name: Target name.
     func directLocalTargetDependencies(path: AbsolutePath, name: String) -> Set<GraphTarget>
 
+    func combinedCondition(to transitiveDependency: GraphDependency, from rootDependency: GraphDependency) -> TargetDependency.Condition.CombinationResult
```
Comment (waltflanagan) [inline Sources/TuistCore/GraphTraverser/GraphTraversing.swift:89]: This still needs comment docs.  maybe this shouldnt even be public but this was the MVP to test the fix.

File: Sources/TuistGenerator/Generator/TargetGenerator.swift [hunk 2]
```diff
@@ -146,11 +146,20 @@ final class TargetGenerator: TargetGenerating {
...
+
             try dependencies.forEach { dependency in
-                let target = nativeTargets[targetSpec.name]!
-                let dependency = nativeTargets[dependency.target.name]!
-                _ = try target.addDependency(target: dependency)
+                let nativeTarget = nativeTargets[targetSpec.name]!
+                let nativeDependency = nativeTargets[dependency.target.name]!
+                let pbxTargetDependency = try nativeTarget.addDependency(target: nativeDependency)
+                let path = dependency.path 
+                if case let .condition(condition) = graphTraverser.combinedCondition(to: .target(name: dependency.target.name, path: dependency.path), from: target),
```
Comment (waltflanagan) [inline Sources/TuistGenerator/Generator/TargetGenerator.swift:159]: this all could probably be cleaned up some as well.  We're missing intersecting with the supported platforms of a target like we do with `PBXBuildFile`.  we may want to pull this into a protocol and extension that can be applied to any xcodeproj type that supports filters.

**Review by danyf90 — APPROVED** [review]
