### PR TITLE
Macro support via Dependencies.swift

### LINKED ISSUE #5488: Missing support for SwiftPackageManager macros
### What happened?

When Swift package containing Swift macro added, tuist fetch failed with error messages below.
It seems like the issue #5435 not fixed yet.

### How do we reproduce it?

1. `mkdir Test`
2. `cd Test`
3. `tuist init --platform ios`
4. `echo 3.28.0 > .tuist-version`
5. `touch Tuist/Dependencies.swift`
6. Open `Tuist/Dependencies.swift` and edit as:
```swift
import ProjectDescription

let dependencies = Dependencies(
    swiftPackageManager: [
        .remote(url: "https://github.com/lukepistrol/SFSymbolsMacro", requirement: .exact("0.4.1")),
    ],
    platforms: [.iOS]
)
```
7. `tuist fetch`
8. Open `Tuist/ProjectDescriptionHelpers/Project+Templates.swift` and edit as:
```swift
// Tuist/ProjectDescriptionHelpers/Project+Templates.swift:L23
private static func makeFrameworkTargets(name: String, platform: Platform) -> [Target] {
    let sources = Target(name: name,
            platform: platform,
            product: .framework,
            bundleId: "io.tuist.\(name)",
            infoPlist: .default,
            sources: ["Targets/\(name)/Sources/**"],
            resources: [],
            dependencies: [
                .external(name: "SFSymbolsMacro") // insert here
            ])
    ...
}
```
9. `tuist generate`

### Error log

```sh
Found an inconsistency between target destinations `[TuistGraph.Destination.iPhone, TuistGraph.Destination.macWithiPadDesign, TuistGraph.Destination.iPad]` and deployment target `macOS`
Found deployment platforms (macOS) missing corresponding destination
Target SFSymbolsMacro has platforms 'iOS' and product 'staticFramework' and depends on target SFSymbolsMacroImpl of type 'Swift Macro' and platforms 'iOS' which is an invalid or not yet supported combination.
Target SFSymbolsMacroImpl has platform 'iOS' and product 'Swift Macro' which is an invalid or not yet supported combination.
Target SFSymbolsMacroImpl has platform 'iOS' and product 'Swift Macro' which is an invalid or not yet supported combination.
Fatal linting issues found
```

### macOS version

13.5.1

### Tuist version

3.28.0

### Xcode version

15.0

### PR DESCRIPTION
**Pull request by waltflanagan**
Resolves #5488 

### Short description 📝

This allows non-macos targets to depend on packages that provide macros.

### How to test the changes locally 🧐

Run `fetch` and `generate` against the fixture `framework_with_swift_macro`.  Framework should build when depending on packages that provide macros via `Dependencies.swift`

### Contributor checklist ✅

- [x] The code has been linted using run `make workspace/lint-fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

File: Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift [hunk 1]
```diff
@@ -628,7 +675,7 @@ extension ProjectDescription.DeploymentTargets {
         packageName _: String
     ) throws -> Self {
         if type == .macro {
-            return .macOS(minDeploymentTargets[.macOS] ?? oldestVersions(for: Version(5, 9, 0)).macOS!)
+            return .macOS("14.0")
```
Comment (waltflanagan) [inline Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift:678]: This probably should change? maybe? i was getting warnings when hacking on it so I'm not entirely sure what we want long term, but setting to 14 works.

File: Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift [hunk 2]
```diff
@@ -240,6 +242,31 @@ public final class PackageInfoMapper: PackageInfoMapping {
...
+        var macroDependencies = Set<ResolvedDependency>()
+
+        while !macroTargetsNames.isEmpty {
+            guard let targetName = macroTargetsNames.popFirst() else {
+                continue
+            }
+
+            if visited.contains(targetName) {
+                continue
+            }
```
Comment (danyf90) [inline Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift:257]:
```suggestion
            guard let targetName = macroTargetsNames.popFirst(), !visited.contains(targetName) {
                continue
            }
```

File: Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift [hunk 3]
```diff
@@ -240,6 +242,31 @@ public final class PackageInfoMapper: PackageInfoMapping {
                     }
             }
 
+        var macroTargetsNames = Set(packageInfos.values.flatMap { $0.targets.filter { $0.type == .macro }.map(\.name) })
+//        let macroDependencies = resolvedDependencies.filter { macroTargetsNames.contains($0.key) }.flatMap({ $0.value })
```
Comment (danyf90) [inline Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift:246]: This can be removed, right?
```suggestion
```

File: Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift [hunk 4]
```diff
@@ -240,6 +242,31 @@ public final class PackageInfoMapper: PackageInfoMapping {
                     }
             }
 
+        var macroTargetsNames = Set(packageInfos.values.flatMap { $0.targets.filter { $0.type == .macro }.map(\.name) })
```
Comment (danyf90) [inline Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift:245]: nit: let's try to be specific with the name, this also includes their dependencies, right?
```suggestion
        var macroTargetsAndDescendants = Set(packageInfos.values.flatMap { $0.targets.filter { $0.type == .macro }.map(\.name) })
```

**Review by danyf90 — APPROVED** [review]
Can we bump TCA dependency in `app_with_spm_dependencies` fixture to make sure it compiles fine? 🙏

File: Tests/TuistBuildAcceptanceTests/BuildAcceptanceTests.swift [hunk 5]
```diff
@@ -91,7 +91,8 @@ final class BuildAcceptanceTestFrameworkWithSwiftMacroIntegratedWithXcodeProjPri
     func test_framework_with_swift_macro_integrated_with_xcode_proj_primitives() async throws {
         try setUpFixture("framework_with_native_swift_macro")
         try await run(FetchCommand.self)
-        try await run(BuildCommand.self, "Framework")
+        try await run(BuildCommand.self, "Framework", "--platform", "macos")
```
Comment (fortmarek) [inline Tests/TuistBuildAcceptanceTests/BuildAcceptanceTests.swift:94]: Do we build for all platforms if they're not specified?

**Review by fortmarek — APPROVED** [review]
👏 

As @danyf90, it would be great to bump the TCA to make sure that dependency builds 😌

File: Tests/TuistBuildAcceptanceTests/BuildAcceptanceTests.swift (hunk 5 above)
Comment (waltflanagan) [reply Tests/TuistBuildAcceptanceTests/BuildAcceptanceTests.swift:94]: Currently any target that has multiple platforms will error for things like `tuist build`,  it makes sense to just build for all platforms but that work was out of scope for initial support.
