### PR TITLE
Fix Fourier issues

### LINKED ISSUE #3623: Meta-Tuist build test failing, not recognized by CI
Currently, the Meta-Tuist build test is failing with the following error:

```
`ArgumentParser` is not a valid configured external dependency
```

There are two separate issues here:
1. `./fourier build tuist all` is failing. I am not sure if this is intended behavior; is it supposed to succeed without running `generate` first?
2. The CI is not properly recognizing the failure as such, so the test seems to be passing.

### PR DESCRIPTION
**Pull request by ezraberch**
Closes #3623.

1. Fetch dependencies when running `./fourier build tuist all`.
2. If an external call is unsuccessful, `fourier` will now stop and return `1`. Current behavior is to ignore the error and continue (so always returning `0`).

CI failures are expected until #3620 is merged.

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]

**Review by pepibumur — APPROVED** [review]
Changes look good. We can merge once CI is happy 😀

**Review by fortmarek — APPROVED** [review]
@ezraberch the CI should pass now if you rebase ✅

File: projects/tuist/features/step_definitions/test.rb [hunk 1]
```diff
@@ -22,7 +22,7 @@
 end
 
 Then(/^tuist tests and cleans the project$/) do
-  require 'byebug'; byebug;
+  require "byebug"; byebug
```
Comment (pepibumur) [inline projects/tuist/features/step_definitions/test.rb:25]: Ouch, we shouldn't have this here.
