### PR TITLE
Fix parsing of `conditon` on SPM `.product` dependencies

### LINKED ISSUE #5295: Tuist still generates targets for incompatible dependencies
### What happened?

When generating a project with a swift package manager dependency containing a conditional package like this for another platform:
```
                .product(name: "Datadog", package: "dd-sdk-ios", condition: .when(platforms: [.iOS])),
                .product(name: "DatadogCrashReporting", package: "dd-sdk-ios", condition: .when(platforms: [.iOS])),
```
Tuist will still include a `datadog_watchos` dependency in the tree (and all transitive dependencies obviously). In our case, Datadog's SDK won't compile for watchOS, so this poses a pretty big issue for us, meaning our project won't compile!
If I manually edit the graph.json and remove the `datadog_watchos` (and related) entries, I can `tuist generate` and compile the project just fine, so this appears to be something tuist is doing that it shouldn't be.

### How do we reproduce it?

1. Use this demo project: https://github.com/Mstrodl/watchos-dependency-demo
2. Run `tuist fetch`
3. Then `tuist generate`
4. Build the watch app
5. Note the presence of the `datadog_watchos` dependency

### Error log

image
Note the `Datadog_watchos` dependencies

### macOS version

13.4.1

### Tuist version

3.21.0

### Xcode version

Version 15.0 beta 3 (15A5195k)

### PR DESCRIPTION
**Pull request by waltflanagan**
SPM `.product()` dependencies contain 4 fields, not three.  We need to account for all of them in order to properly parse condition and use it when resolving dependencies.

In order to properly parse the output of `dump-package` we need to account for 4 fields in the current SPM implementation.  SPM has been like this for the last three years, so this should work with both Xcode 14 and 15 generated packages. 

https://github.com/apple/swift-package-manager/blob/3e8328e3de533dd1ed570aee83a90d3b20fdb5fe/Sources/PackageDescription/Target.swift#L59

Raw json:
```
      "product" : [
            "Datadog",
            "dd-sdk-ios",
            null,
            {
              "platformNames" : [
                "ios"
              ]
            }
```

Fixes #5295

### How to test the changes locally 🧐

Run tuist against the demo project in #5295 

### Contributor checklist ✅

- [x] The code has been linted using run `mise run lint:fix`
- [ ] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]
Do we have any example we can add to our fixture to make sure it doesn't break again in the future?

**Comment by waltflanagan** [comment]
@danyf90 working to add that as well, enum equality is slowing things down 😄

**Review by apps4everyone — APPROVED** [review]

File: fixtures/app_with_spm_dependencies/LocalSwiftPackage/Package.swift [hunk 1]
```diff
@@ -8,9 +8,15 @@ let package = Package(
...
     platforms: [.iOS(.v13)],
     products: [.library(name: "Styles", targets: ["Styles"])],
+    dependencies: [
+        .package(path: "../LocalSwiftPackageB")
+    ],
     targets: [
         .target(
             name: "Styles",
+            dependencies: [
+                .product(name: "LibraryA", package: "LocalSwiftPackageB", condition: .when(platforms: [.macOS]))
```
Comment (danyf90) [inline fixtures/app_with_spm_dependencies/LocalSwiftPackage/Package.swift:18]: Would compilation fail if condition is not parsed? If not, are we really testing it?

**Review by danyf90 — APPROVED** [review]

File: fixtures/app_with_spm_dependencies/LocalSwiftPackage/Package.swift (hunk 1 above)
Comment (waltflanagan) [reply fixtures/app_with_spm_dependencies/LocalSwiftPackage/Package.swift]: yes, the source itself includes `import AppKit` when we go to build the iOS app it would fail if the condition is not applied.
