### PR TITLE
Fix target linter warnings for target products that allow dots and hyphens

### LINKED ISSUE #6289: Tuist prints out warnings when using Braze
### What happened?

Running `tuist generate` when having Braze as a dependency will print out warnings.

This is regression between Tuist 4.11.0 and 4.13.0. I did not check if this happens with 4.12.0.

### How do we reproduce it?

1. Add Braze as a dependency `.package(url: "https://github.com/braze-inc/braze-swift-sdk", exact: "7.3.0")`
2. Run `tuist install && tuist generate` and you will observe the warnings

### Error log

```
The following warnings need attention:
 · Invalid product name 'braze-swift-sdk_BrazeUI'. This string must contain only alphanumeric (A-Z,a-z,0-9), and underscore (_) characters.
 · Invalid product name 'braze-swift-sdk_BrazeKitResources'. This string must contain only alphanumeric (A-Z,a-z,0-9), and underscore (_) characters.
 ```

### macOS version

14.4.1

### Tuist version

4.13.0

### Xcode version

15.3

### PR DESCRIPTION
**Pull request by kapitoshka438**
Resolves #6289
### Short description 📝

This PR fixes the target linter to allow dot (".") and hyphen ("-") in some types of target products.

### How to test the changes locally 🧐

Generate the `app_with_spm_dependencies` fixture. Target linter warnings for BrazeUI dependency bundles should not appear anymore.

### Contributor checklist ✅

- [x] The code has been linted using run `mise run lint:fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [ ] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

File: Sources/TuistGenerator/Linter/TargetLinter.swift [hunk 1]
```diff
@@ -76,14 +76,19 @@ class TargetLinter: TargetLinting {
...
+        ]
+        let allowsExtraCharacters = productsAllowingExtraCharacters.contains(target.product)
+        if allowsExtraCharacters {
+            allowed.formUnion(CharacterSet(charactersIn: ".-"))
         }
 
         if target.productName.unicodeScalars.allSatisfy(allowed.contains) == false {
             let reason =
-                "Invalid product name '\(target.productName)'. This string must contain only alphanumeric (A-Z,a-z,0-9)\(allowsDot ? ", period (.)" : ""), and underscore (_) characters."
+                "Invalid product name '\(target.productName)'. This string must contain only alphanumeric (A-Z,a-z,0-9)\(allowsExtraCharacters ? ", period (.), hyphen (-)" : ""), and underscore (_) characters."
```
Comment (pepicrft) [inline Sources/TuistGenerator/Linter/TargetLinter.swift:91]: This message is not true for products that are not included in `productsAllowingExtraCharacters`, is it?

**Review by pepicrft — APPROVED** [review]
Thanks for fixing this @kapitoshka438. Only a small thing regarding the message and we should be good to go.

**Review by fortmarek — APPROVED** [review]

File: Sources/TuistGenerator/Linter/TargetLinter.swift (hunk 1 above)
Comment (kapitoshka438) [reply Sources/TuistGenerator/Linter/TargetLinter.swift:91]: Period and hyphen are allowed in product name for app, bundle, commandLineTool and, I believe, many other types of targets but framework.
I can check all types where Xcode automatically replaces these characters with underscore.

Comment (kapitoshka438) [reply Sources/TuistGenerator/Linter/TargetLinter.swift:91]: Well, I've checked almost all targets in Xcode and there's only one type where it transforms the product name by replacing dots and hyphens with underscores. It's Framework. When you add it, Xcode automatically sets its Product Name to `$(TARGET_NAME:c99extidentifier)` so that, for example, a target named `my.frame-work` gets Product Name as `my_frame_work`.
I've also tried to add such targets (`.staticFramework` and `.framework`) in a Tuist project and it works differently, replacing only hyphens: `My.Frame-work` -> `My.Frame_work`.

File: Sources/TuistGraph/Models/Target.swift [hunk 2]
```diff
@@ -83,7 +83,13 @@ public struct Target: Equatable, Hashable, Comparable, Codable {
...
         self.destinations = destinations
         self.bundleId = bundleId
-        self.productName = productName ?? name.sanitizedModuleName
+        if let productName {
+            self.productName = productName
+        } else if product == .framework || product == .staticFramework {
+            self.productName = "$(TARGET_NAME:c99extidentifier)"
+        } else {
+            self.productName = "$(TARGET_NAME)"
+        }
```
Comment (kwridan) [inline Sources/TuistGraph/Models/Target.swift:92]: `productName` is used in a few different contexts within Tuist in addition to setting the underlying build setting. While Xcode can recognise variables  - sadly Tuist can't and will regress a few things within it where the `productName` is relied upon to derive various xcodeProj element / product names.

The logic needs to continue to be defined in tuist code as opposed to via variables.

**Review by kwridan — COMMENTED** [review]
Thanks @kapitoshka438 

I wonder if a different bug is causing the product names for Braze to get mangled and not propagated correctly - I don't have a lot of context on the SPM integration but from what I can see in the package manifest all target names seem sane with no hyphens or dots!

https://github.com/braze-inc/braze-swift-sdk/blob/main/Package.swift

File: Sources/TuistGraph/Models/Target.swift [hunk 3]
```diff
@@ -83,7 +83,13 @@ public struct Target: Equatable, Hashable, Comparable, Codable {
         self.product = product
         self.destinations = destinations
         self.bundleId = bundleId
-        self.productName = productName ?? name.sanitizedModuleName
+        if let productName {
+            self.productName = productName
+        } else if product == .framework || product == .staticFramework {
```
Comment (kwridan) [inline Sources/TuistGraph/Models/Target.swift:88]: is the discrepancy of what constitutes of valid product names documented anywhere? I wasn't aware frameworks an applications have different rules 🤔

File: Sources/TuistGraph/Models/Target.swift (hunk 2 above)
Comment (kapitoshka438) [reply Sources/TuistGraph/Models/Target.swift:92]: Ah makes sense. I'll revert this. It's not really related to the original issue. Anyway it's a pity that we can't use such variables. But maybe someday we will. )

File: Sources/TuistGraph/Models/Target.swift (hunk 3 above)
Comment (kapitoshka438) [reply Sources/TuistGraph/Models/Target.swift]: It's the result of my manual research. I created an empty project in Xcode and created all possible types of targets with names containing dots and hyphens. `Framework` is the only target where Xcode transforms Product Name by setting it to "$(TARGET_NAME:c99extidentifier)". Product Name for all other targets was just "$(TARGET_NAME)"

Comment (kapitoshka438) [reply Sources/TuistGraph/Models/Target.swift]: I would suggest to try to bring the same approach in Tuist someday. But, taking into account your previous comment, not in this PR.

**Review by pepicrft — APPROVED** [review]
