### PR TITLE
fix(server): retry on :closed_for_writing 

### LINKED ISSUE #8104: Packages in registry not being updated
### What happened?

Looks like some packages in our registry aren't being updated, e.g. getsentry/sentry-cocoa

Image

### How do we reproduce it?

1. Try to use the Tuist registry for `getsentry/sentry-cocoa` for a version released after Aug 1
...

### Error log

-

### macOS version

n/a

### Tuist version

n/a

### Xcode version

n/a

### PR DESCRIPTION
**Pull request by cschmatzler**
GitHub sometimes closes the HTTP connection unexpectedly.
This PR 
1. adjusts pool settings so it happens less often
2. adds the `closed_for_writing` reason to Req retries as its not included in the defaults

Closes #8104

### CODE REVIEW

File: server/lib/tuist/github/client.ex [hunk 1]
```diff
@@ -111,7 +126,8 @@ defmodule Tuist.GitHub.Client do
            headers: default_headers(token),
            decode_body: false,
            finch: Tuist.Finch,
-           into: File.stream!(path, [:write])
+           into: File.stream!(path, [:write]),
+           retry: &retry/2
```
Comment (pepicrft) [inline server/lib/tuist/github/client.ex:130]: Is this with exponential back off?

**Review by pepicrft — APPROVED** [review]

File: server/lib/tuist/github/client.ex (hunk 1 above)
Comment (cschmatzler) [reply server/lib/tuist/github/client.ex:130]: Yes it's by default.
> :retry_delay - if not set, which is the default, the retry delay is determined by the value of the Retry-After header on HTTP 429/503 responses. If the header is not set, the default delay follows a simple exponential backoff: 1s, 2s, 4s, 8s, ...

https://hexdocs.pm/req/Req.Steps.html#retry/1
