### PR TITLE
Fix for `tuist fetch` not failing when run outside of a Tuist project

### LINKED ISSUE #5047: Tuist fetch succeeds if run in a folder without a tuist project
### What happened?

`tuist fetch` should fail if not run in a tuist-related folder, similar to what `tuist generate` does

### How do we reproduce it?

1. Be in any folder without a tuist project (even an empty one)
2. Run `tuist fetch`

### Error log

```
tuist fetch
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
```

### macOS version

12.3

### Tuist version

3.16.0

### Xcode version

14.2.0

### PR DESCRIPTION
**Pull request by havebeenfitz**
Resolves #5047 

### Short description 📝

`tuist fetch` won't succeed in any directory now. Internal checks from `ManifestLoader` will fail the attempt.

```
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Manifest not found at path /Users/user/Library/Developer/Xcode/DerivedData/Tuist-cswbwinvydwhonfpadailaybahcs/Build/Products/Debug
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
Program ended with exit code: 1
```

### How to test the changes locally 🧐

Pass an argument "fetch" on launch

### Contributor checklist ✅

- [x] The code has been linted using run `./fourier lint tuist --fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase
- [x] Contributors have checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

File: Sources/TuistKit/Services/FetchService.swift [hunk 1]
```diff
@@ -63,12 +63,6 @@ final class FetchService {
     }
 
     private func fetchDependencies(path: AbsolutePath, update: Bool, with plugins: TuistGraph.Plugins) throws {
-        guard FileHandler.shared.exists(
```
Comment (danyf90) [inline Sources/TuistKit/Services/FetchService.swift:66]: Fetch is also for plugins, not just dependencies.
I think we should just make the command fail if we can't find the Project.swift file

**Review by danyf90 — CHANGES_REQUESTED** [review]

File: Sources/TuistKit/Services/FetchService.swift (hunk 1 above)
Comment (havebeenfitz) [reply Sources/TuistKit/Services/FetchService.swift:66]: fetchPlugins relies on `configLoader` and `pluginService` to load plugins and will fail if there are issues

Comment (havebeenfitz) [reply Sources/TuistKit/Services/FetchService.swift:66]: Apart from plugins error handling, we could have `Workspace.swift` instead of `Project.swift. I think all that is pretty well handled by the dedicated services with their readable errors

Comment (danyf90) [reply Sources/TuistKit/Services/FetchService.swift:66]: Oh maybe it's changed recently, anyway I would make it fail if not manifest is found (either project or workspace), there should already be a method for that if I recall correctly

Comment (havebeenfitz) [reply Sources/TuistKit/Services/FetchService.swift:66]: That'll happen inside a `DependenciesModelLoader` `loadDependencies` method.`manifestLoader` will try to load the manifest and will fail the same way `tuist generate` does through `Generator` and `ManifestGraphLoader`

Comment (danyf90) [reply Sources/TuistKit/Services/FetchService.swift:66]: Yes but it would make tuist fetch fail on projects without dependencies, and that's potentially a breaking change (e.g. someone might have some integration running tuist fetch in all their projects, regardless from the presence of dependencies)

Comment (havebeenfitz) [reply Sources/TuistKit/Services/FetchService.swift:66]: Makes sense, I'll change that, thank you

Comment (havebeenfitz) [reply Sources/TuistKit/Services/FetchService.swift:66]: I'm not sure if it's a good idea to use the whole manifestGraph loader, I could just use these lines inside a method

```swift
let manifests = manifestLoader.manifests(at: path)
guard manifests.contains(.workspace) || manifests.contains(.project) else {
    throw ManifestLoaderError.manifestNotFound(path)
}
```

But then `ManifestLoaderError` is used outside of its scope

Comment (danyf90) [reply Sources/TuistKit/Services/FetchService.swift:66]: I agree we should use ManifestLoading and not ManifestGrahpLoading.
What about adding a method to ManifestLoading?
Something like:
```
    public func validateHasProjectOrWorkspaceManifest(at: path) throws {
        let manifests = manifestLoader.manifests(at: path)
        guard manifests.contains(.workspace) || manifests.contains(.project) else {
            throw ManifestLoaderError.manifestNotFound(path)
        }
    }
```

**Review by danyf90 — CHANGES_REQUESTED** [review]

File: Sources/TuistKit/Services/FetchService.swift (hunk 1 above)
Comment (havebeenfitz) [reply Sources/TuistKit/Services/FetchService.swift:66]: Fair enough. Added the method and tests

**Review by danyf90 — APPROVED** [review]

**Review by danyf90 — APPROVED** [review]

**Review by danyf90 — APPROVED** [review]
