### PR TITLE
Fixed a bug where turning on and off the rendering of markdown files in Workspace config wouldn't turn off rendering properly and would stay in read-only mode (fixes #5196)

### LINKED ISSUE #5196: Turning off `renderMarkdownReadme:` parameter still renders the Reamde in read-only mode instead of edit mode
### What happened?

See our Slack thread [conversation](https://tuistapp.slack.com/archives/C018QG7U7SN/p1684764786985939?thread_ts=1684492937.382289&cid=C018QG7U7SN) with @kwridan triggering this bug.

The `renderMarkdownReadme: false` flag in `Workspace` was added in this [Issue #4356](https://github.com/tuist/tuist/issues/4356#issuecomment-1094827048).

But there is currently a small bug that the `MyApp.xcworkspace/.xcodesamplecode.plist` file is not deleted when the flag is turned on and off again.

Current workaround:

1. Either manually delete that file and re-open Xcode:

```
rm MyApp.xcworkspace/.xcodesamplecode.plist
open MyApp.xcworkspace
```

2. or to delete the workspace and re-generate it again:

```
rm -rf MyApp.xcworkspace
tuist generate
open MyApp.xcworkspace
```

### How do we reproduce it?

1. Create a `Workspace.swift` file with the flag turned on (or use this [fixture](https://github.com/tuist/tuist/blob/main/projects/tuist/fixtures/ios_app_with_custom_workspace/Workspace.swift)):

```
let workspace = Workspace(name: "MyApp",
                          projects: [
                            "."
                          ],
                          additionalFiles: [
                            "README.md"
                            "Workspace.swift"
                          ],
                          generationOptions: .options(
                            enableAutomaticXcodeSchemes: false,
                            autogeneratedWorkspaceSchemes: .disabled,
                            renderMarkdownReadme: true // turn this on
                          ))
```

2. `tuist generate`
3. `open MyApp.xcworkspace`
4. open `README.md` (Xcode will open it in read-only mode)
5. close Xcode
6. Now edit `Workspace.swift` and turn off the flag:

```
                            renderMarkdownReadme: false // turn this off
```
7. `tuist generate`
8. open workspace and `README.md` again (Xcode still renders in read-only mode)

Now applying workaround:
9. `rm MyApp.xcworkspace/.xcodesamplecode.plist`
10. open workspace and `README.md` again (Xcode finally opens it in edit mode ✅ )

### Error log

Xcode still renders README.md in read-only mode instead of edit mode.

### macOS version

13.3.1

### Tuist version

3.19.0

### Xcode version

14.2

### PR DESCRIPTION
**Pull request by Buju77**
Resolves https://github.com/tuist/tuist/issues/5196

### Short description 📝

> The `.xcodesamplecode.plist` file wasn't removed again when turning off `renderMarkdownReadme` flag in Workspace config.

### How to test the changes locally 🧐

> 1. Create a workspace with `renderMarkdownReadme: true`
> 2. Open the README.md in Xcode and verify it is in read-only mode
> 3. Now change the flag to false `renderMarkdownReadme: false`
> 4. Check the Readme in Xcode again and it should be in edit-mode now (it remained in read-only mode before the fix)

### Contributor checklist ✅

- [✅] The code has been linted using run `./fourier lint tuist --fix`
- [✅] The change is tested via unit testing or acceptance testing, or both
- [✅] The title of the PR is formulated in a way that is usable as a changelog entry
- [✅] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

File: Sources/TuistKit/Mappers/Workspace/TuistWorkspaceRenderMarkdownMapper.swift [hunk 1]
```diff
@@ -5,21 +5,18 @@ import TuistSupport
...
         let tuistGeneratedFileDescriptor = FileDescriptor(
             path: workspace
                 .workspace
                 .xcWorkspacePath
                 .appending(
                     component: ".xcodesamplecode.plist"
                 ),
-            contents: try PropertyListEncoder().encode([String]())
+            contents: try PropertyListEncoder().encode([String]()),
+            state: workspace.workspace.generationOptions.renderMarkdownReadme ? .present : .absent // bugfix: #5196
```
Comment (danyf90) [inline Sources/TuistKit/Mappers/Workspace/TuistWorkspaceRenderMarkdownMapper.swift:19]:
```suggestion
            state: workspace.workspace.generationOptions.renderMarkdownReadme ? .present : .absent 
```

**Review by danyf90 — APPROVED** [review]

**Review by pepicrft — APPROVED** [review]

**Comment by pepicrft** [comment]
@all-contributors add @Buju77 for code

**Comment by Buju77** [comment]
@pepicrft I've rebased the branch and CI is now also finally green as well ✅

**Review by danyf90 — APPROVED** [review]
