### PR TITLE
Replace EnvUpdater with EnvInstaller

### LINKED ISSUE #4069: Tuistenv update not updating tuistenv
I noticed that `tuist update` was not finding 2.7.1. After manually running the install script, it was able to find find 2.7.1. So it seems that my version of `tuistenv` was from before the change from version detection based on Changelog to version detection based on github tags.

Conclusion: `tuist update` is not updating `tuistenv`. Here's the relevant code:

https://github.com/tuist/tuist/blob/1b993a20fef8f1e9742d81a264e9ec8e42b847f3/Sources/TuistEnvKit/Updater/EnvUpdater.swift#L30-L33

So it's looking for a local copy of the install script, and running it. But there is no such local copy, so it fails.

I'm unsure how this is supposed to work. Is there even supposed to be a local copy of the install script? If so, when should it be downloaded, and to where?

There's also a secondary bug here. Since the process fails to launch, rather than launching successfully then failing, the error checking in `System` does not catch it. So it fails silently.

### PR DESCRIPTION
**Pull request by ezraberch**
Resolves #4069.

### Short description 📝

This PR replaces `EnvUpdater` with `EnvInstaller`, which downloads the latest version of `tuistenv.zip` in a matter similar to how `Installer` downloads `tuist.zip`. It is then renamed and moved to wherever the existing executable is.

### How to test the changes locally 🧐

`swift run tuistenv update`

Note: You will need to remove the latest version of tuist first, as the updater won't do anything if the latest version is already installed.

### Checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://docs.tuist.io/contributors/testing-strategy/).
- [ ] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.

### CODE REVIEW

File: Sources/TuistEnvKit/Updater/Updater.swift [hunk 1]
```diff
@@ -44,10 +40,14 @@ final class Updater: Updating {
...
                 logger.notice("Installing new version available \(highestRemoteVersion)")
                 try installer.install(version: highestRemoteVersion.description)
+                logger.info("Updating tuistenv", metadata: .section)
+                try envInstaller.install(version: highestRemoteVersion.description)
             }
         } else {
             logger.notice("No local versions available. Installing the latest version \(highestRemoteVersion)")
             try installer.install(version: highestRemoteVersion.description)
+            logger.info("Updating tuistenv", metadata: .section)
+            try envInstaller.install(version: highestRemoteVersion.description)
```
Comment (danyf90) [inline Sources/TuistEnvKit/Updater/Updater.swift:50]: I woould move this outside of the if/else, and change the inner if in a guard in case "There are no updates available"

File: Sources/TuistEnvKit/Installer/EnvInstaller.swift [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+    static func == (lhs: EnvInstallerError, rhs: EnvInstallerError) -> Bool {
+        switch (lhs, rhs) {
+        case let (.versionNotFound(lhsVersion), .versionNotFound(rhsVersion)):
+            return lhsVersion == rhsVersion
+        case let (.incompatibleSwiftVersion(lhsLocal, lhsExpected), .incompatibleSwiftVersion(rhsLocal, rhsExpected)):
+            return lhsLocal == rhsLocal && lhsExpected == rhsExpected
+        default:
+            return false
+        }
+    }
```
Comment (danyf90) [inline Sources/TuistEnvKit/Installer/EnvInstaller.swift:48]: Isn't this synthesized by the compiler?

File: Sources/TuistEnvKit/Installer/EnvInstaller.swift [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+    // MARK: - Attributes
+
+    let buildCopier: BuildCopying
+    let versionsController: VersionsControlling
+
+    // MARK: - Init
+
+    init(buildCopier: BuildCopying = BuildCopier(),
+         versionsController: VersionsControlling = VersionsController())
+    {
```
Comment (danyf90) [inline Sources/TuistEnvKit/Installer/EnvInstaller.swift:62]:
```suggestion
    init(
        buildCopier: BuildCopying = BuildCopier(),
        versionsController: VersionsControlling = VersionsController()
    ) {
```

File: Sources/TuistEnvKit/Installer/EnvInstaller.swift [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+            bundleURL: URL(string: "https://github.com/tuist/tuist/releases/download/\(version)/tuistenv.zip")!,
+            version: version,
+            temporaryDirectory: temporaryDirectory
+        )
+    }
+
+    func installFromBundle(bundleURL: URL,
+                           version: String,
+                           temporaryDirectory: AbsolutePath) throws
+    {
```
Comment (danyf90) [inline Sources/TuistEnvKit/Installer/EnvInstaller.swift:86]:
```suggestion
    func installFromBundle(
        bundleURL: URL,
        version: String,
        temporaryDirectory: AbsolutePath
    ) throws {
```

File: Sources/TuistEnvKit/Installer/EnvInstaller.swift [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
+        let installationPath = try System.shared.which("tuist")
+
+        // Download bundle
+        logger.notice("Downloading TuistEnv version \(version)")
+        let downloadPath = temporaryDirectory.appending(component: Constants.envBundleName)
+        try System.shared.run(["/usr/bin/curl", "-LSs", "--output", downloadPath.pathString, bundleURL.absoluteString])
+
+        // Unzip
+        logger.notice("Installing...")
```
Comment (danyf90) [inline Sources/TuistEnvKit/Installer/EnvInstaller.swift:95]:
```suggestion
        logger.notice("Installing…")
```

File: Sources/TuistEnvKit/Installer/EnvInstaller.swift [hunk 6]
```diff
@@ -0,0 +1,108 @@
...
+        try System.shared.run(["/usr/bin/unzip", "-q", downloadPath.pathString, "tuistenv", "-d", temporaryDirectory.pathString])
+
+        // Copy
+        let cpArgs = ["cp", temporaryDirectory.appending(component: "tuistenv").pathString, installationPath]
+        do {
+            try System.shared.run(cpArgs)
+        } catch {
+            try System.shared.run(["sudo"] + cpArgs)
+        }
```
Comment (danyf90) [inline Sources/TuistEnvKit/Installer/EnvInstaller.swift:104]: Have you checked that it works fine even if the destination is the program that is doing the copy itself?

**Review by danyf90 — CHANGES_REQUESTED** [review]

File: Sources/TuistEnvKit/Installer/EnvInstaller.swift (hunk 2 above)
Comment (ezraberch) [reply Sources/TuistEnvKit/Installer/EnvInstaller.swift:48]: It should be. I took this from `Installer.swift`, so I'll make the changes there as well.

**Review by danyf90 — APPROVED** [review]
