### PR TITLE
Change the implementation of auto generated schemes

### LINKED ISSUE #2639: Unexpected auto-generated schemes test action
**Describe the bug**
When generating a project with Tuist it automatically tries to generate schemes for targets. This heuristic is currently implemented in [AutogeneratedSchemesProjectMapper.swift](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift). The code there is iterating through all targets and for each target it searches for all test bundles that have the target as a dependency. This means that for a target A the scheme test action runs all the test bundles of targets that dependencies on target A which is in my opinion unexpected.

**To Reproduce**
Setup a project like this:

- Target A (static lib) & Target ATests (test bundle)
- Target B (static lib) & Target BTests (test bundle)
- Target C (static lib) & Target CTests (test bundle)

In this setup Target B should depend on Target A and Target C on Target B. And it will result that the auto generated scheme of Target A will run Target ATests, Target BTests and Target CTests.

**Expected behavior**
In the above example it should only run the Target ATests and we should change the heuristic to check if there is a test bundle target with the same name as target name but prefixed with `Tests`.

### PR DESCRIPTION
**Pull request by FranzBusch**
Resolves #2639 

### Short description 📝

This changes the implementation of the auto generated schemes to only pick test bundles that are naming like the target and have a suffix with `Tests`, `UITests` or `IntegrationTests`

### Checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase.
- [x] The changes have been tested following the [documented guidelines](https://tuist.io/docs/contribution/testing-strategy/).
- [x] The `CHANGELOG.md` has been updated to reflect the changes. In case of a breaking change, it's been flagged as such.
- [ ] In case the PR introduces changes that affect users, the documentation has been updated.

### CODE REVIEW

File: Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift [hunk 1]
```diff
@@ -81,6 +93,16 @@ final class AutogeneratedSchemesProjectMapperTests: TuistUnitTestCase {
...
+                testScheme(
+                    target: targetBTests,
+                    projectPath: projectPath,
+                    testTargetName: "BUITests"
+                ),
+                testScheme(
+                    target: targetBTests,
+                    projectPath: projectPath,
+                    testTargetName: "BIntegrationTests"
+                ),
```
Comment (kwridan) [inline Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift:105]: I believe we'll need to update the test helper `testScheme` to allow specifying an array of test target names to cater for the new changes - as in this test case `B` target will have 3 test targets in its scheme.

e.g.

```swift
XCTAssertEqual(
            got.schemes,
            [
                testScheme(
                    target: targetA,
                    projectPath: projectPath,
                    testTargetNames: ["ATests"]
                ),
                testScheme(
                    target: targetATests,
                    projectPath: projectPath,
                    testTargetNames: ["ATests"]
                ),
                testScheme(
                    target: targetB,
                    projectPath: projectPath,
                    testTargetNames: ["BIntegrationTests", "BTests", "BUITests"]
                ),
                testScheme(
                    target: targetBTests,
                    projectPath: projectPath,
                    testTargetNames: ["BTests"]
                ),
                testScheme(
                    target: targetBUITests,
                    projectPath: projectPath,
                    testTargetNames: ["BUITests"]
                ),
                testScheme(
                    target: targetBIntegrationTests,
                    projectPath: projectPath,
                    testTargetNames: ["BIntegrationTests"]
                ),
            ]
        )
```

_(heh re-examing `testScheme` I can see how it can be confusing in this context 😅, perhaps a better choice would have been `makeScheme`)_

File: Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift [hunk 2]
```diff
@@ -90,7 +90,7 @@ public final class AutogeneratedSchemesProjectMapper: ProjectMapping {
         } else {
             // The test targets that are dependant on the given target.
             return project.targets
-                .filter { $0.product.testsBundle && $0.dependencies.contains(.target(name: target.name)) }
+                .filter { $0.product.testsBundle && ($0.name == "\(target.name)Tests" || $0.name == "\(target.name)UITests" || $0.name == "\(target.name)IntegrationTests") }
```
Comment (kwridan) [inline Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift:93]: minor: could possibly have a private helper method `isAssociatedTestTarget` _(or something equivalent)_

File: Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift [hunk 3]
```diff
@@ -30,6 +30,16 @@ final class AutogeneratedSchemesProjectMapperTests: TuistUnitTestCase {
             product: .unitTests,
```
Comment (kwridan) [inline Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift:30]: It's worth adding another test case to reproduce the scenario you described in the issue to verify the fix addresses it :)

e.g.

`ATests` > `[A, B]`

**Review by kwridan — COMMENTED** [review]
This is a great first code contribution @FranzBusch 🎉

The changes look good! left some minor inline comments _(one should hopefully address the test failure)_. The other CI check is failing on swift format, you can run `bundle exec rake style_correct` to re-format the code.

Lastly, mind updating the CHANGELOG file to include a new entry for this change.

Thanks

**Comment by kwridan** [comment]
@all-contributors add @FranzBusch for code

File: Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift (hunk 3 above)
Comment (FranzBusch) [reply Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift:30]: I covered it with my first test case to make sure only the proper targets are picked up. Is that enough for you @kwridan ?

**Comment by FranzBusch** [comment]
@kwridan @pepibumur Could you help me in getting this merged. I am a bit lost why the test if failing

**Review by kwridan — APPROVED** [review]
Thanks for the updates @FranzBusch!

re: the test failure it seems odd, I wouldn't have thought your changes would impact any of the caching features - will run it locally to see what I can find.

**Comment by kwridan** [comment]
Locally running the failing test in question passes on this PR for me - seems we have some sort of environment flake 😞

```
./bin/fourier test tuist acceptance features/cache-frameworks.feature
```

cc: @tuist/core

**Comment by laxmorek** [comment]
I had a similar issue with `cache-frameworks.feature` in my last PR. I re-run jobs and it passed. I don't know where was a problem. 🤔 

Definitely `features/cache-frameworks.feature` should no pass "randomly".

**Comment by FranzBusch** [comment]
@tuist/core could somebody re-run the job for me?

**Comment by fortmarek** [comment]
> could somebody re-run the job for me?

done @FranzBusch 👍 

Hopefully, it will pass now and we should the test's flakiness soon as it creates a lot of confusion for contributors when they see a test fail when they did not even introduce any changes to that part of the codebase

**Comment by laxmorek** [comment]
It passed now. Definitely we must fix it.

**Comment by FranzBusch** [comment]
@kwridan What do I need to do to get this merged? :)

**Review by fortmarek — APPROVED** [review]
Thanks @FranzBusch for your contribution!
