### PR TITLE
fix(cli): fix bundle accessor for Obj-C external static frameworks with resources

### LINKED ISSUE #9156: `BundleNotFound` exception for StaticFrameworks since 4.128.2
### What happened?

For dependencies like [SVProgressHUD](https://github.com/SVProgressHUD/SVProgressHUD) the codebase crashes at runtime with a `BundleNotFound` exception during bundle resolution, when used as a StaticFramework.

### How do we reproduce it?

[CLImageEditorTuistSample.zip](https://github.com/user-attachments/files/24711529/CLImageEditorTuistSample.zip)

### Error log

Image

### macOS version

26.2

### Tuist version

4.128.2

### Xcode version

16.0.2

### PR DESCRIPTION
**Pull request by pepicrft**
## Summary

This PR fixes the `BundleNotFound` exception for external packages configured as static frameworks with resources (like SVProgressHUD or CLImageEditor).

### What changed

1. **Aligned local and external static framework embedding**: External static frameworks with resources are now embedded, just like local ones. Previously, I had reverted embedding for external dependencies thinking it was causing issues, but the actual problem was that the Info.plist generated for those frameworks had an incorrect bundle identifier.

2. **Simplified bundle generation logic**: Static frameworks (both local and external) no longer generate separate resource bundles. Resources stay inside the framework, which gets embedded.

3. **Updated the Obj-C bundle accessor**: The accessor now mirrors SwiftPM's approach while adding Tuist-specific framework locations. It first checks for embedded `.framework` bundles (where Tuist places resources for static frameworks), then falls back to looking for `.bundle` files (SwiftPM's standard approach). This maintains backward compatibility while supporting Tuist's static framework resource embedding.

### Assumptions

This assumes that external dependencies are using the generated bundle accessor to find their resources, which is a safe assumption since that's how SwiftPM packages access their resources.

### Test plan

- Added an acceptance test fixture with SVProgressHUD configured as a staticFramework to prevent regressions

Closes #9156

### CODE REVIEW

File: cli/Sources/TuistCore/Graph/GraphTraverser.swift [hunk 1]
```diff
@@ -1492,7 +1492,7 @@ public class GraphTraverser: GraphTraversing {
         let target = graphTarget.target
         if target.product.isDynamic { return true }
         if target.product == .staticFramework, target.containsResources || target.containsMetalFiles {
-            return graphTarget.project.type == .local
+            return true
```
Comment (pepicrft) [inline cli/Sources/TuistCore/Graph/GraphTraverser.swift:1495]: As mentioned in the description, I wrongly assumed that the issue that we had with external packages was  not a bug but some assumptions in third-party packages regarding how bundles are accessed, but it turned out that wasn't the case, and it was just how we generated the Info.plist, so I'm reverting it.

File: cli/Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift [hunk 2]
```diff
@@ -232,6 +232,15 @@ final class DependenciesAcceptanceTestAppAlamofire: TuistAcceptanceTestCase {
     }
 }
 
+final class DependenciesAcceptanceTestAppWithObjCStaticFrameworkWithResources: TuistAcceptanceTestCase {
+    func test_app_with_objc_static_framework_with_resources() async throws {
+        try await setUpFixture("generated_app_with_objc_static_framework_with_resources")
+        try await run(InstallCommand.self)
+        try await run(GenerateCommand.self)
+        try await run(BuildCommand.self, "App")
```
Comment (pepicrft) [inline cli/Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift]: Need to find a way to run the app and check that it doesn't blow up.

**Review by fortmarek — APPROVED** [review]
