### PR TITLE
fix(cli): filter out dependencies with unsatisfied trait conditions

### LINKED ISSUE #9218: Bug on how Tuist transform Swift Package with Triats
### What happened?

I'm not sure why, but it seems that Tuist has some bug with how it transform Swift Package with traits.

The attached project where I consume [Apollo version 1.7.0](https://github.com/apollographql/apollo-ios/releases/tag/1.7.0) -> which depends on [SQLite](https://github.com/stephencelis/SQLite.swift)
 -> Which depends on [SQLCipher](https://github.com/sqlcipher/SQLCipher.swift)

SQLite released a new version that introduce traits into their SPM definition (at least I think so) which cause Tuist to interoperate it as an external dependency that is consumed via some targets

### How do we reproduce it?

1) Download the attached zip file and unzip it
2) cd into `TuistSPMTraitsSQLCipherExample`
3) Run `tuist install`
4) Run `tuist generate`

See the error

[TuistSPMTraitsSQLCipherExample.zip](https://github.com/user-attachments/files/24799915/TuistSPMTraitsSQLCipherExample.zip)

```sh
✖ Error 
  `SQLCipher` is not a valid configured external dependency 

  Sorry this didn’t work. Here’s what to try next: 
   ▸ If the error is actionable, address it
   ▸ If the error is not actionable, let's discuss it in the Troubleshooting & how to
   ▸ If you are very certain it's a bug, file an issue

```

### Error log

```sh
✖ Error 
  `SQLCipher` is not a valid configured external dependency 

  Sorry this didn’t work. Here’s what to try next: 
   ▸ If the error is actionable, address it
   ▸ If the error is not actionable, let's discuss it in the Troubleshooting & how to
   ▸ If you are very certain it's a bug, file an issue

```

### macOS version

26.2 (25C56)

### Tuist version

4.122.0

### Xcode version

26.0.1

### PR DESCRIPTION
**Pull request by pepicrft**
## Summary
- Filters out Swift package dependencies whose trait conditions are not satisfied
- When a target dependency has a condition with traits (e.g., `.when(traits: ["SQLCipher"])`), the dependency is now correctly skipped if none of the required traits are enabled

## Context
This PR depends on tuist/XcodeGraph#470 which adds the `traits` field to `PackageConditionDescription`.

The issue was that packages like SQLite.swift have dependencies that are conditionally included based on traits. For example, the `SQLCipher` dependency is only included when the `SQLCipher` trait is enabled. However, Tuist was still trying to resolve these dependencies regardless of trait conditions, causing "is not a valid configured external dependency" errors.

Fixes #9218

### CODE REVIEW

File: examples/xcode/generated_spm_dependency_with_trait_conditions/Tuist/Package.swift [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+
+    let packageSettings = PackageSettings(
+        productTypes: [:]
+    )
+#endif
+
+let package = Package(
+    name: "App",
+    dependencies: [
+        .package(url: "https://github.com/apollographql/apollo-ios.git", exact: "1.7.0"),
```
Comment (danibachar) [inline examples/xcode/generated_spm_dependency_with_trait_conditions/Tuist/Package.swift:15]: Something I forgot to do in my example is pinning the specific problematic version of SQLite - 0.15.5

Comment (danibachar) [reply examples/xcode/generated_spm_dependency_with_trait_conditions/Tuist/Package.swift:15]:
```suggestion
        .package(url: "https://github.com/apollographql/apollo-ios.git", exact: "1.7.0"),
        .package(url: "https://github.com/stephencelis/SQLite.swift.git", exact: "0.15.5"),
```

File: examples/xcode/generated_spm_dependency_with_trait_conditions/README.md [hunk 2]
```diff
@@ -0,0 +1,3 @@
+# SPM dependency with trait conditions
+
+This example contains an app that depends on the [Apollo iOS](https://github.com/apollographql/apollo-ios) SDK. Apollo depends on [SQLite.swift](https://github.com/stephencelis/SQLite.swift), which has a trait-conditional dependency on SQLCipher. This fixture validates that Tuist correctly filters out dependencies whose trait conditions are not satisfied.
```
Comment (danibachar) [inline examples/xcode/generated_spm_dependency_with_trait_conditions/README.md:3]:
```suggestion
This example contains an app that depends on the [Apollo iOS](https://github.com/apollographql/apollo-ios) SDK. Apollo depends on [SQLite.swift](https://github.com/stephencelis/SQLite.swift), which has a trait-conditional dependency on SQLCipher. This fixture validates that Tuist correctly filters out dependencies whose trait conditions are not satisfied.

Specifically, the SQLite version [0.15.5](https://github.com/stephencelis/SQLite.swift/releases/tag/0.15.5) introduced those traits. As such we pinned that version in the Package.swift file
```
