### PR TITLE
Fixes non-deterministic condition resolution

### LINKED ISSUE #5746: [Multiplatform]- (non-deterministic) Incorrect platform conditions when using multi platform app target with extensions
### What happened?

Currently I see a weird behaviour when I use platform filters in a multi module, multi platform project. I have a single multi platform app target (supporting macOS and iOS). On iOS I include a widget extension which I don't have on macOS. 

Both, the `App` target and the `WidgetExtension` target are using targets from other modules (projects) in the workspace. As soon as I link the `WidgetExtension` target to the `App` target with platform filters for `iOS`, randomly the targets(direct and transitive) from the other modules are also only getting the `iOS` platform filter applied which then breaks the `macOS` implementation since I need the transitive dependencies there also for the `macOS` platform. This behaviour is unfortunately not deterministic, meaning sometimes the generation works correctly and sometimes it does not resulting into the issue described above. 

The graph of dependencies: 

graph

A wrongly generated workspaces looks like this, where normally `ModuleC` and `Resolver` would also need "Always used" otherwise they fail to load on `macoS` when requested

Screenshot 2023-12-30 at 15 16 31

A correctly generated App target should look like this, where all dependencies are always used and only the `WidgetExtension` target has the `iOS` platform filter applied:

Screenshot 2023-12-30 at 15 25 55

### How do we reproduce it?

1. Use the attached sample project [multiplatform_app_with_transitive_dependencies.zip](https://github.com/tuist/tuist/files/13798305/multiplatform_app_with_transitive_dependencies.zip)

2. Run `tuist fetch` && `tuist generate`
3. Run `tuist generate` until the wrong dependency tree from the first screenshot is shown

### Error log

No error log 

### macOS version

14.0

### Tuist version

3.37.0

### Xcode version

15.1.0

### PR DESCRIPTION
**Pull request by waltflanagan**
Fixes #5746

The optimization that was used elsewhere in the GraphTraverser to skip nodes actually introduced a logic error in the case where different dependency paths lead to the same transitive dependency with different conditions.  Depending on the ordering of traversal we would end up with different nodes being skipped which would lead to different results. 

### How to test the changes locally 🧐

Run against test project in #5746.

### Contributor checklist ✅

- [x] The code has been linted using run `make workspace/lint-fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

File: Sources/TuistCore/Graph/GraphTraverser.swift [hunk 1]
```diff
@@ -728,62 +728,65 @@ public class GraphTraverser: GraphTraversing {
         return references
     }
 
+    @Atomic var conditionCache = [GraphEdge: PlatformCondition.CombinationResult]()
```
Comment (pepicrft) [inline Sources/TuistCore/Graph/GraphTraverser.swift:731]: > different dependency paths lead to the same transitive dependency with different conditions.

Introducing a cache to solve the non-determinism makes me skeptical. If different paths lead to different conditions, shouldn't we traverse all the paths and merge the conditions? Also, won't this non-determinism exist across Tuist runs?

Comment (danyf90) [reply Sources/TuistCore/Graph/GraphTraverser.swift:731]: ➕ 1
I have either misunderstood the problem, or we should merge the results rather than getting the first one we hit

**Review by kwridan — COMMENTED** [review]
Thanks @waltflanagan 

Sadly this change causes a huge regression in generation time 🙈

For comparison here's a table with the generation times of our workspace (~ 160 projects) by version:

| Version  | Time   | Delta     | Notes                                         |
|----------|--------|-----------|-----------------------------------------------|
| 3.27.1   | 3.77s  |           | Pre multi-platform conditions additions       |
| 3.37.0   | 4.65s  | ⚠️ + 23%   | Latest main with platform condition additions |
| PR #5750 | 84.34s | ‼️ +1,714% |                                               |

An alternate worth exploring is skipping certain paths that aren't real linkable dependencies (e.g. App > Extension) where it's done for convenience and Tuist automatically interprets those dependencies as dependant products to include but not necessarily to traverse when computing what to link / embed.

We have some precedence for this in the static warning linter https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift#L189

**Comment by waltflanagan** [comment]
@kwridan would you be able to run the profiler so we can get some more detail on what is contributing to that increase? I'm curious if there is anything that could be done with the atomic access for the cache as well. (e.g. NSLock vs os_unfair_lock) I'm also curious if we end up seeing any contention between threads with cache access or if this is all just the N^N runtime of the problem. 

I'll look into building a performance test with an appropriate level of complexity that we can have in the codebase for testing this as well.

**Comment by alexanderwe** [comment]
@kwridan 

> An alternate worth exploring is skipping certain paths that aren't real linkable dependencies (e.g. App > Extension) where it's done for convenience and Tuist automatically interprets those dependencies as dependant products to include but not necessarily to traverse when computing what to link / embed.
> 
> We have some precedence for this in the static warning linter https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift#L189

But I think here we need to also pay attention to dependencies of the extension, because if I am not mistaken they are embedded in the `.app` target and therefore the dependencies of the extension need to be traversed as well. 

Dependencies of widget extension are not embedded in the extension but in the app target:
Screenshot 2024-01-02 at 17 07 55

Screenshot 2024-01-02 at 17 10 39

File: Sources/TuistCore/Graph/GraphTraverser.swift (hunk 1 above)
Comment (waltflanagan) [reply Sources/TuistCore/Graph/GraphTraverser.swift:731]: removing the `visited` check fixed the bug.  Depending on which node was visited first, we would end up skipping it with subsequent runs of `combinedCondition` and end up with an incorrect result.  Always walking all paths was the solution.  

The cache was added because always walking all paths quickly becomes expensive.

**Comment by waltflanagan** [comment]
@kwridan I implemented a simple project of ~160 frameworks that were in a simple tree structure where I have ~6 levels where all frameworks on level 1 depend on all frameworks on level two (roughly 20-30 deps per framework).  This is generating in ~3s here (no source traversal) with the current `NSCache` implementation of caching.  I did some remedial profiling with this project and found using a plain `Dictionary` has performance issues with copy-on-write.  

I'm curious what you see with the latest implementation and if you have any other tips on adding complexity to this sample project I have to better mimic your setup so we can build a complex fixture for stress testing.

**Comment by kwridan** [comment]
> But I think here we need to also pay attention to dependencies of the extension, because if I am not mistaken they are embedded in the .app target and therefore the dependencies of the extension need to be traversed as well, or do I misunderstand something here ?

Thanks for highlighting this @alexanderwe, you are absolutely correct they need to be accounted for for the embed phase! 

> @kwridan would you be able to run the profiler so we can get some more detail on what is contributing to that increase? 

Sure will take a look to see what stands out 👍 

> @kwridan I implemented a simple project of ~160 frameworks that were in a simple tree structure where I have ~6 levels where all frameworks on level 1 depend on all frameworks on level two (roughly 20-30 deps per framework). 

Thanks @waltflanagan for the follow up on this 🙏, I should have added more details the workspace has ~160 projects (but each has several targets, so we have a total of around 380 targets!). We have a [fixture generator](https://github.com/tuist/tuist/tree/main/Sources/tuistfixturegenerator) in Tuist that could be useful not sure if you saw it, though it's quite simple and generate any complicated graphs.

Will do another round of testing with the latest changes.

File: Sources/TuistCore/Graph/GraphTraverser.swift (hunk 1 above)
Comment (pepicrft) [reply Sources/TuistCore/Graph/GraphTraverser.swift]: >  Always walking all paths was the solution.

This is the part that I missed. Thanks for clarifying it 🙏🏼

File: Tests/TuistCoreTests/Graph/GraphTraverserTests.swift [hunk 2]
```diff
@@ -4601,6 +4601,67 @@ final class GraphTraverserTests: TuistUnitTestCase {
         XCTAssertEqual(result.1, platformCondition)
     }
 
+    // https://github.com/tuist/tuist/issues/5746
+    func test_transitiveTargetDependenciesWhenIntermediateDependenciesHaveConditions() throws {
```
Comment (kwridan) [inline Tests/TuistCoreTests/Graph/GraphTraverserTests.swift:4605]: Thanks for including this 👍 

A few small suggestions:
- is it worth replicating the use case @alexanderwe reported (e.g. adding an extension in the example)? The scenario does replicate it but thought may be more clear to show a real use cases where you would specify a platform condition (e.g. from first glance I was thinking was the condition needed here :D) 
- For this test to catch the issue it needs to be run repeatedly, while possible in Xcode UI would be good to enforce it from the test _(we do something similar in the [stable generation test](https://github.com/tuist/tuist/blob/main/Tests/TuistIntegrationTests/Generator/StableStructureIntegrationTests.swift#L15))_


e.g.


```swift
// ...
// When
        let appToFrameworkCResults = (0..<100).map { _ in
            subject.combinedCondition(
                to: frameworkCDependency,
                from: appDependency
            )
        }

        let appToFrameworkDResults = (0..<100).map { _ in
            subject.combinedCondition(
                to: frameworkDDependency,
                from: appDependency
            )
        }

        // Then
        XCTAssertTrue(appToFrameworkCResults.allSatisfy { $0 == .condition(nil) })
        XCTAssertTrue(appToFrameworkDResults.allSatisfy { $0 == .condition(nil) })
```

**Review by kwridan — APPROVED** [review]
Thanks again @waltflanagan 

The latest updates are a significant boost 🚀 we're now back to ~4.39s!!

I profiled the previous iteration and indeed it was to do with Dictionary's copy!

```
1.02min   24.7%	1.02min	 	 outlined copy of GraphDependency
55.18 s   22.4%	55.18 s	 	 specialized _NativeDictionary.copy()
54.81 s   22.2%	54.81 s	 	 outlined consume of GraphDependency
32.54 s   13.2%	32.54 s	 	 destroy for GraphEdge
15.62 s    6.3%	15.62 s	 	 specialized UnsafeMutablePointer.initialize(to:)
4.64 s    1.8%	4.64 s	 	 DYLD-STUB$$swift_bridgeObjectRetain
3.90 s    1.5%	0 s	 	 closure #1 in Atomic.store(newValue:)
3.47 s    1.4%	3.47 s	 	 DYLD-STUB$$swift_bridgeObjectRelease
2.46 s    0.9%	2.46 s	 	 outlined copy of PlatformCondition.CombinationResult
2.15 s    0.8%	2.15 s	 	 destroy for PlatformCondition.CombinationResult
1.80 s    0.7%	1.80 s	 	 GraphTraverser.combinedCondition(to:from:)
```

**Review by pepicrft — APPROVED** [review]

File: Tests/TuistCoreTests/Graph/GraphTraverserTests.swift (hunk 2 above)
Comment (waltflanagan) [reply Tests/TuistCoreTests/Graph/GraphTraverserTests.swift:4605]: the product type of a target isn't taken into account at the graph traverser level.  if dependencies relationships are defined in the graph (which may take product types into account externally). This case could be replicated with frameworks that have capabilities that have platform specific features that rely on a system frameworks.   e.g. `FrameworkA` provides something for `macOS` relying on `StoreKit`, and then separately `FrameworkB` provides something on `iOS`  that relies on `StoreKit`.  if you have a Multiplatform (iOS/macOS) app that uses both frameworks, then `StoreKit` should be included in call cases without filters.  I don't think that the extension case needs to be part of this unit test.  Are you thinking any other places that could include something like this to help folks more generally understand conditions? 

for the second bit, I can add doing this a few times since it should be basically free due to caching now.

Comment (waltflanagan) [reply Tests/TuistCoreTests/Graph/GraphTraverserTests.swift:4605]: to explain a little more since I'm sure this PR will be referenced in the future:

The bug manifested because `visited` would in some cases contain `FrameworkB` when computing the filters needed for `StoreKit`.  This would mean that only the filters of `FrameworkA` would be included in the union calculation and that would result in the wrong final condition being calculated.
