### PR TITLE
fix: add support for Swift interoperabilityMode setting

### LINKED ISSUE #5678: Unable to fetch package with interoperabilityMode
### What happened?

We have private Swift Package containing multiple products used in main projects. I've created new library that uses swift target which depends on c++/Objective-C target. Xcode requires to add:
```swift
swiftSettings: [
    .interoperabilityMode(.Cxx)
]
``` 
to such target, but tuist seems to not recognize that setting.

### How do we reproduce it?

Add swift package dependency with `.interoperabilityMode(.Cxx)` in Package.swift file.

### Error log

We received an error that we couldn't handle:
    - Localized description: The data couldn’t be read because it is missing.
    - Error: keyNotFound(CodingKeys(stringValue: "name", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "targets", intValue: nil), _JSONKey(stringValue: "Index 12", intValue: 12), CodingKeys(stringValue: "settings", intValue: nil), _JSONKey(stringValue: "Index 2", intValue: 2)], debugDescription: "No value associated with key CodingKeys(stringValue: \"name\", intValue: nil) (\"name\").", underlyingError: nil))

If you think it's a legit issue, please file an issue including the reproducible steps: https://github.com/tuist/tuist/issues/new/choose
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### macOS version

14.2

### Tuist version

3.35.5

### Xcode version

15.1

### PR DESCRIPTION
**Pull request by pepicrft**
## Summary

This PR adds support for Swift packages that use the `interoperabilityMode` setting (`.Cxx`, `.C`) by mapping them to the appropriate `SWIFT_OBJC_INTEROP_MODE` build setting in Xcode.

## Changes

- Added handling for `interoperabilityMode` in `SettingsMapper.swift` to map:
  - `.Cxx` → `SWIFT_OBJC_INTEROP_MODE = "objcxx"`
  - `.C` → `SWIFT_OBJC_INTEROP_MODE = "objc"`
- Updated `PackageInfoMapper.swift` to properly handle the setting without treating it as a dependency
- Added test fixture using spine-runtimes package which uses `.interoperabilityMode(.Cxx)`

## Test Plan

- [x] Added spine-runtimes package to test fixture which uses `.interoperabilityMode(.Cxx)`
- [x] Manually tested that packages with interoperability mode now generate projects successfully
- [x] Verified that the appropriate build settings are applied in the generated Xcode project

Fixes #5678

### CODE REVIEW

File: Package.swift [hunk 1]
```diff
@@ -577,7 +577,7 @@ let package = Package(
             url: "https://github.com/apple/swift-openapi-urlsession", .upToNextMajor(from: "1.0.2")
         ),
         .package(url: "https://github.com/tuist/Path", .upToNextMajor(from: "0.3.0")),
-        .package(url: "https://github.com/tuist/XcodeGraph", .upToNextMajor(from: "1.16.6")),
+        .package(url: "https://github.com/tuist/XcodeGraph", branch: "rename-claude-to-agent"),
```
Comment (pepicrft) [inline Package.swift]: I need to revert this one before merging.

File: cli/Fixtures/ios_app_with_spm_dependencies/Project.swift
Comment (fortmarek) [inline cli/Fixtures/ios_app_with_spm_dependencies/Project.swift:1]: I'd create a fixture that's dedicated to `Spine` (`app_with_spine`). This monolith fixture is already really slow to run.
