### PR TITLE
fix(cli): Fix buildable folder resource placement for static targets

### LINKED ISSUE #8547: Static framework targets place buildable-folder resources on the framework instead of the generated bundle
### What happened?

When a target uses buildable folders and its product type is .staticFramework, Tuist still generates the helper bundle target—but the resources from synchronized folders stay attached to the framework target. Static frameworks can’t embed resources directly, so the build fails or the resources simply never ship.

## Current Result

Resource files and localized assets from the buildable folders are added to the static framework target instead of the generated bundle target. Using the generated resource accessors causes a crash in runtime, as the files aren't found in the bundle:

Image

## Expected Result

Tuist should attach resource-only buildable folders to the generated bundle target, keeping the static framework free of resources while still exposing sources from other synchronized folders, just like the behavior with "regular" Xcode groups:

Image

## Impact

Projects adopting buildable folders for static frameworks can’t build or ship their resources. This blocks adoption of Xcode 16’s buildable folders feature for static products.

### How do we reproduce it?

1. Define a static framework target that uses buildableFolders for both sources and resources (e.g. Sources/ and Resources/).
2. Generate the project with Tuist 4.62+.
3. Open the project in Xcode 16 or 26.
4. Inspect the framework target’s build phases or access a resource via generated resource accessors

### Error log

No error

### macOS version

26

### Tuist version

4.94.0

### Xcode version

26

### PR DESCRIPTION
**Pull request by natanrolnik**
Resolves #8547

Static targets now hand resource-only buildable folders to the generated bundle target, ensuring buildable folder resources don’t stay on static frameworks when buildable folders are used. Updated `ResourcesProjectMapper` tests to cover mixed source/resource folders.

- make ResourcesProjectMapper split buildable folders so resource-only folders move to the generated bundle while source folders remain with the static target
- add coverage in ResourcesProjectMapperTests for mixed source/resource buildable folders and keep terminology inclusive by renaming the shared helper parameter to allowedExtensions

### CODE REVIEW

File: cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift [hunk 1]
```diff
@@ -376,6 +395,33 @@ public class ResourcesProjectMapper: ProjectMapping { // swiftlint:disable:this
...
+                hasExtension(file.path.extension, in: Target.validResourceCompatibleFolderExtensions)
+        }
+    }
+}
+
+private func hasExtension(_ extensionValue: String?, in allowedExtensions: [String]) -> Bool {
+    guard let extensionValue else { return false }
+    return allowedExtensions.contains { $0.caseInsensitiveCompare(extensionValue) == .orderedSame }
+}
+
```
Comment (fortmarek) [inline cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift:539]:
```suggestion

private func hasExtension(_ extensionValue: String?, in allowedExtensions: [String]) -> Bool {
    guard let extensionValue else { return false }
    return allowedExtensions.contains { $0.caseInsensitiveCompare(extensionValue) == .orderedSame }
}
}
```

no need to define this method at the file level

File: cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift [hunk 2]
```diff
@@ -376,6 +395,33 @@ public class ResourcesProjectMapper: ProjectMapping { // swiftlint:disable:this
...
+            return true
+        }
+        return resolvedFiles.contains { file in
+            hasExtension(file.path.extension, in: Target.validResourceExtensions) ||
+                hasExtension(file.path.extension, in: Target.validResourceCompatibleFolderExtensions)
+        }
+    }
+}
+
+private func hasExtension(_ extensionValue: String?, in allowedExtensions: [String]) -> Bool {
```
Comment (fortmarek) [inline cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift]: this can be an extension on `AbsolutePath`, should make the code a bit prettier ✨

File: cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift [hunk 3]
```diff
@@ -376,6 +395,33 @@ public class ResourcesProjectMapper: ProjectMapping { // swiftlint:disable:this
...
+        }
+    }
+
+    fileprivate var containsResourceLikeFiles: Bool {
+        if hasExtension(path.extension, in: Target.validResourceCompatibleFolderExtensions) {
+            return true
+        }
+        return resolvedFiles.contains { file in
+            hasExtension(file.path.extension, in: Target.validResourceExtensions) ||
+                hasExtension(file.path.extension, in: Target.validResourceCompatibleFolderExtensions)
```
Comment (fortmarek) [inline cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift]:
```suggestion
            hasExtension(file.path.extension, in: Target.validResourceExtensions + Target.validResourceCompatibleFolderExtensions)
```

File: cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift [hunk 4]
```diff
@@ -376,6 +395,33 @@ public class ResourcesProjectMapper: ProjectMapping { // swiftlint:disable:this
     }
 }
 
+extension BuildableFolder {
+    fileprivate var containsSourceLikeFiles: Bool {
```
Comment (fortmarek) [inline cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift]: would probably make this a method instead of a variable since needs to go through all files

File: cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift [hunk 5]
```diff
@@ -182,6 +187,20 @@ public class ResourcesProjectMapper: ProjectMapping { // swiftlint:disable:this
         return project.derivedDirectoryPath(for: target).appending(components: Constants.DerivedDirectory.sources, filename)
     }
 
+    private func partitionBuildableFoldersForResources(
```
Comment (fortmarek) [inline cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift:194]: would add a comment here explaining the purpose of this method

**Comment by hiltonc** [comment]
It's possible to have resources nested in a sources folder (that's the case in our setup). Can we support that too?

File: cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift [hunk 6]
```diff
@@ -182,6 +187,20 @@ public class ResourcesProjectMapper: ProjectMapping { // swiftlint:disable:this
...
+        _ folders: [BuildableFolder]
+    ) -> (resourceFolders: [BuildableFolder], remainingFolders: [BuildableFolder]) {
+        folders.reduce(into: (resourceFolders: [BuildableFolder](), remainingFolders: [BuildableFolder]())) { result, folder in
+            if folder.containsSourceLikeFiles {
```
Comment (pepicrft) [inline cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift]: What happens if the buildable folder contains sources and resources? Also, how does Xcode behave if:
- A target of bundle product type has a buildable folder that references sources
- A target of library product type has a buildable folder that references resources

Comment (natanrolnik) [reply cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift]: Great questions @pepicrft!

> What happens if the buildable folder contains sources and resources? 

That's what @hiltonc asks also - a resources folder inside a sources folder - I didn't think about that when fixing the bug, and I'll take that into account.

> A target of bundle product type has a buildable folder that references sources

It builds just fine:

Xcode-2025-11-02 at 11 48 15@2x

> A target of library product type has a buildable folder that references resources

Xcode-2025-11-02 at 11 50 43@2x

It just ignores it (by not having a copy resources build phase) and doesn't let you add resource files to the library target.

My question is:

* Should Tuist warn (or error) if it finds a bundle target with source files, or a library with resources?
* if a buildable folder contains sources and resources on a target of type static framework, how should it behave?

Comment (pepicrft) [reply cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift]: If the behavior of Xcode is the one that we want, then I think we should not warn nor error.

**Comment by pepicrft** [comment]
Thanks @natanrolnik for helping with this one ❤️
