### PR TITLE
fix(server): handle xcresult upload with asynchronously inserted command events

### LINKED ISSUE #7970: Race condition with asynchronous event insertion and xcresult upload
### What happened?

In `TuistAnalyticsServerBackend.swift` we run 
```
            try await analyticsArtifactUploadService.uploadResultBundle(
                resultBundlePath,
                commandEventId: serverCommandEvent.id,
                serverURL: url
            )
```

after uploading the command event.
This calls `get_command_event_by_id` on the server, which can return 404 if the buffer hasn't flushed yet.

We need to make the multipart upload URL independent of the actual event in the database to prevent a dependency on analytics pipeline processing.

### How do we reproduce it?

Run any command with `CI=true`.

### Error log

[10:16:14]: ▸ Testing started
[10:16:17]: ▸ Storing remote selectiveTests. Hold tight...
[10:16:29]: ▸ Uploading run metadata...
[10:17:20]: ▸ Failed to upload run metadata: notFound("The run with ID 114969974536120416 was not found.")
[10:17:20]: ▸ ✔ Success
[10:17:20]: ▸ The project tests ran successfully

### macOS version

-

### Tuist version

-

### Xcode version

-

### PR DESCRIPTION
**Pull request by cschmatzler**
resolves #7970 

In CI, the CLI tries to immediately upload the `xcresult` file after uploading the command event metadata. For that, it requests an upload URL from the server; to generate that URL, the controller queries the event from the database. After #7942, that might lead to a race condition where the event hasn't materialised to the database yet, returning a 404.

This PR solves this by making the upload of the result bundle independent of the database state and just generating the URL based on the event identifier in the request.
1. For Postgres, the behavior stays the same. Events are still inserted synchronously and can be queried for their ID.
2. For Clickhouse, we _need_ to use the legacy integer identifier, since that is now derivable from the UUID. For older CLI versions, we just take the integer from the request, for newer versions, we derive it from the UUID in the request. We cannot derive the UUID from the integer, so the other direction wouldn't work.
3. I've removed test case handling from the controller completely for now, since we're reworking that _right now_ and also are making it asynchronous.

### CODE REVIEW

File: server/lib/tuist_web/controllers/api/analytics_controller.ex [hunk 1]
```diff
@@ -616,58 +616,50 @@ defmodule TuistWeb.API.AnalyticsController do
...
+        {:ok, command_event} ->
+          {:ok, command_event.legacy_id}
 
-      {:error, :not_found} ->
-        {:error, :not_found}
+        _ ->
+          {:error, :not_found}
+      end
     end
   end
```
[the remark this answers is not in the document]
Comment (cschmatzler) [reply server/lib/tuist_web/controllers/api/analytics_controller.ex]: no it doesn't you muppet, postgres uses synchronous inserts and i even explicitly stated that in the PR description

File: server/test/tuist_web/controllers/analytics_controller_test.exs [hunk 2]
```diff
@@ -768,7 +768,7 @@ defmodule TuistWeb.AnalyticsControllerTest do
       upload_id = "12344"
 
       object_key =
-        "#{account.name}/#{project.name}/runs/#{command_event.id}/result_bundle.zip"
+        "#{account.name}/#{project.name}/runs/#{command_event.legacy_id}/result_bundle.zip"
```
Comment (fortmarek) [inline server/test/tuist_web/controllers/analytics_controller_test.exs:771]: I would probably update the tests to use the new id

Comment (cschmatzler) [reply server/test/tuist_web/controllers/analytics_controller_test.exs:771]: I've added an explanation comment to the controller itself as to why this changed to `legacy_id`.
