### PR TITLE
fix(cli): restore static framework resources without regressions

### LINKED ISSUE #7381: XcodeProj: Unable to build main target with local SPM dependency with Image assets
### What happened?

[Xcode 15 has introduced](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Asset-Catalogs) autogenerated types for Image and Color assets to provide compile check of the referenced assets.

The dependency target build fails due to missing autogenerated types/extensions for `ImageResource`, if it is defined as `.external` with `.staticFramework` product type and contains `.xcassets` in Resources.

It's possible to overcome build issue by manually adding `Images.xcassets` catalog to the target's "Copy Bundle Resource" build phase.

### How do we reproduce it?

1. Use attached sample project [failing_build_with_dependency_with-resources.zip](https://github.com/user-attachments/files/19072437/failing_build_with_dependency_with-resources.zip)
2. Generate Xcode Workspace `mise x -- tuist install && mise x -- tuist generate`
3. Try to compile app

### Error log

```
DependencyWithImages/Sources/DependencyWithImages/DependencyWithImages.swift:8:20: error: type 'String' has no member 'tuistLogo'
            Image(.tuistLogo)
```

Image

### macOS version

14.7.4

### Tuist version

4.43.2

### Xcode version

16.2

### PR DESCRIPTION
**Pull request by pepicrft**
## Summary
- Restore static framework resource handling so resources stay on the framework target and Xcode can synthesize asset types.
- Fix static framework bundle accessors (Swift + ObjC) to search framework/app bundle locations with a safe fallback.
- Add acceptance fixture/test for local SPM dependency with asset catalogs to prevent regressions.

## Testing
- `mise x -- tuist test TuistGeneratorAcceptanceTests` (completed; test action reported no tests to run in this scheme)

## Related
- Fixes #7381
- Related: #7006
- Related: #7232

### CODE REVIEW

File: cli/Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift [hunk 1]
```diff
@@ -143,7 +143,29 @@ extension Target {
...
+            }
+        }
+    }
+
+    private func isSourceLike(path: AbsolutePath) -> Bool {
+        guard let `extension` = path.extension else { return false }
+
+        let validExtensions = Target.validSourceExtensions
+            + Target.validSourceCompatibleFolderExtensions
+            + ["h", "hpp", "hh", "hxx"]
```
Comment (pepicrft) [inline cli/Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift]: Isn't there a similar attribute to check header extensions in Target.?

File: cli/Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift [hunk 2]
```diff
@@ -143,7 +143,29 @@ extension Target {
...
-        !resources.resources.isEmpty || !coreDataModels.isEmpty
+        if !resources.resources.isEmpty || !coreDataModels.isEmpty { return true }
+        return buildableFolders.contains { folder in
+            folder.resolvedFiles.contains { file in
+                !isSourceLike(path: file.path)
+            }
+        }
+    }
+
+    private func isSourceLike(path: AbsolutePath) -> Bool {
```
Comment (pepicrft) [inline cli/Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift]: This logic here can be simpler

File: cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift [hunk 3]
```diff
@@ -37,14 +37,15 @@ public class ResourcesProjectMapper: ProjectMapping { // swiftlint:disable:this
...
     public func mapTarget(_ target: Target, project: Project) async throws -> ([Target], [SideEffectDescriptor]) {
-        if target.resources.resources.isEmpty, target.coreDataModels.isEmpty,
-           !target.sources.contains(where: { $0.path.extension == "metal" }),
-           !(try await buildableFolderChecker.containsResources(target.buildableFolders)),
-           !containsSynthesizedFilesInBuildableFolders(target: target, project: project)
-        { return (
-            [target],
-            []
-        ) }
+        let containsResources = !target.resources.resources.isEmpty || !target.coreDataModels.isEmpty
```
Comment (pepicrft) [inline cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift]: Can you use the extensions in target to check if there are resources? That logic accounts for buildable folders too. I think there's an opportunity to simplify things here. For example `containsSynthesizedFilesInBuildableFolders` shouldn't be here in my opinion.

File: cli/Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift (hunk 1 above)
Comment (pepicrft) [reply cli/Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift]: No existing helper for header extensions in Target, so I added a small private `headerExtensions` set and simplified `isSourceLike` to use it (lowercased, case-insensitive). Let me know if you prefer promoting this to a shared helper.

File: cli/Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift (hunk 2 above)
Comment (pepicrft) [reply cli/Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift]: Simplified the `containsResources` helper and `isSourceLike` to a lowercased extension check + header set; this should be much easier to follow now.

File: cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift (hunk 3 above)
Comment (pepicrft) [reply cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift]: Updated `ResourcesProjectMapper` to rely on `target.containsResources` (covers buildable folders + resource extensions) and removed `containsSynthesizedFilesInBuildableFolders`/`buildableFolderChecker.containsResources` from the resource check. Only metal sources stay as a separate signal.

File: cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift [hunk 4]
```diff
@@ -53,7 +52,8 @@ public class ResourcesProjectMapper: ProjectMapping { // swiftlint:disable:this
         let bundleName = "\(project.name)_\(sanitizedTargetName)"
         var modifiedTarget = target
 
-        if !target.supportsResources {
+        let canHostResources = target.supportsResources || target.product == .staticFramework
```
Comment (fortmarek) [inline cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift]: shouldn't we change the value of `supportsResources` in `XcodeGraph` over handling this here since static frameworks _can_ now host resources?

That would also simplify https://github.com/tuist/tuist/pull/9081/files#diff-fd82aca7a4046536b40e4923717b57aa7d9b94763a1ec03805753747fdd6a38aR217 and https://github.com/tuist/tuist/pull/9081/files#diff-fd82aca7a4046536b40e4923717b57aa7d9b94763a1ec03805753747fdd6a38aR111

File: cli/Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift [hunk 5]
```diff
@@ -29,6 +29,17 @@ struct GeneratorAcceptanceTests {
...
 
+    @Test(.withFixture("generated_local_spm_dependency_with_assets"), .withMockedLogger())
+    func local_spm_dependency_with_assets() async throws {
+        // Given
+        let fixtureDirectory = try #require(TuistTest.fixtureDirectory)
+
+        // When
+        try await TuistTest.run(InstallCommand.self, ["--path", fixtureDirectory.pathString])
+        try await TuistTest.run(GenerateCommand.self, ["--path", fixtureDirectory.pathString, "--no-open"])
+        try await TuistTest.run(BuildCommand.self, ["TuistSampleProject", "--path", fixtureDirectory.pathString])
```
Comment (fortmarek) [inline cli/Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift]: we deprecated `tuist build`, so we should use `xcodebuild` directly instead

**Comment by nicorichard** [comment]
I've been looking at Tuist for our very large brownfield project. We use local swift packages as the vehicle for modularity, and also happen to use generated accessors across many different modules.

This will do so much towards allowing us to evaluate Tuist without bloodshed. Thank you.

File: cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift (hunk 4 above)
Comment (pepicrft) [reply cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift]: [Moved it there](https://github.com/tuist/XcodeGraph/pull/451) @fortmarek

**Comment by pepicrft** [comment]
> I've been looking at Tuist for our very large brownfield project. We use local swift packages as the vehicle for modularity, and also happen to use generated accessors across many different modules.

@nicorichard I'll have this one merged today ;)

**Comment by nicorichard** [comment]
Just reporting back to say that I pulled the new release (CLI 4.122.2) and my codebase just ran its first successful build using a Tuist generated project 🎉

**Comment by adarhef** [comment]
@pepicrft @fortmarek Thank you for doing this! I've been waiting for this for a long time.

After testing this change I spotted a couple of issues I think you might want to take a look at though.

One thing is I think there's an issue with the generated `module` Bundle extension in unit tests.
The check for `canImport(XCTest)` fails when running from a test target even if it explicitly depends on `xctest`. It only passes if the main target depends on `xctest`. I think a more robust choice would be to check `if ProcessInfo.processInfo.processName == "xctest"`.
If I manually change the check so it passes, the logic for stepping outside into the build folder to find the bundle seems incorrect as well. 
I think `Bundle(for: UnitTestBundleFinder.self)` seems to return the `main` bundle in a static framework (which is the test bundle in an XCTest). Then `resourceURL?.appendingPathComponent("..")` steps out one level from the `Resources` folder, which puts you in the `Contents` folder of the test bundle. 
If we start with the `bundleURL.appending(component: "..")`, it finds the framework successfully from a unit test.

Another issue seems to be with Metal files in a static framework. A framework with Metal files will also contain a `default.metallib` as a generated resource, therefore the framework needs to be copied into the app bundle, but it currently isn't.

**Comment by pepicrft** [comment]
Thanks @adarhef. I'm taking a look at it.

**Comment by barbaramartina** [comment]
Hello. Would some of you help me with a link to documentation about how to set the resources synthesiser? 
Unfortunately Strings catalog resources are not generated. I read that as long as string catalogs are in the resources configured folder, Tuist should automatically generate accessors. 
Is that correct? 

This is my configuration:
- Tuist CLI 4.130.2
- Static frameworks
- String catalogs under Resources folder
- String catalogs are properly included in the Bundle Copy phase of the framework. 
- if I use String(localized: “my.string.key”, bundle: .module) the translation is properly read
- I can not use Text(MyFrameworkNameReources.Strings.myStringkey) since Strings are not generated at all. 

If someone could hint me with ideas that would be great.
